markdown: CommonMarkGhPages
plugins:
  - jekyll-commonmark-ghpages
  - jekyll-relative-links
commonmark:
  options: ["UNSAFE", "SMART"]
  extensions: ["table", "strikethrough", "autolink", "tagfilter"]
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - doc/MANUAL.de.md
exclude:
  - software
  - hardware
  - mechanical
