# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Matthias Blankertz <matthias@blankertz.org>
---
name: Run pytests
"on":
  push:

jobs:
  Check-Pytest:
    runs-on: ubuntu-22.04-full
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          path: git
      - name: Get dependencies
        run: |
          python -m venv test-venv
          test-venv/bin/pip install -r git/software/tests/requirements.txt
      - name: Run pytest
        run: |
          . test-venv/bin/activate &&
          cd git/software &&
          pytest
