name: Check code formatting
on:
  push:

jobs:
  Check-C-Format:
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake clang-format
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run clang format
        run: |
          cmake software -B build
          cmake --build build -- check-format
  Check-Python-Flake8:
    runs-on: ubuntu-22.04
    steps:
      - name: Get Flake8
        run: |
          python3 -m venv flake-venv
          flake-venv/bin/pip install flake8==7.0
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          path: git
      - name: Check python
        run: |
          cd git/software && (
            find src -iname '*.py' -exec ../../flake-venv/bin/flake8 {} +
            find tests -iname '*.py' -exec ../../flake-venv/bin/flake8 {} +
            find modules -iname '*.py' -exec ../../flake-venv/bin/flake8 {} +
            )
  Check-Bash-Shellcheck:
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          path: git
      - name: Check bash scripts
        run: |
          cd git/software &&
          find . -path ./lib -prune -o -name "*.sh" -exec shellcheck {} +
